fao_main_homepage:
    pattern:  /
    defaults: { _controller: FaoMainBundle:Default:docs }

fao_main_terminos:
    pattern:  /terminos
    defaults: { _controller: FaoMainBundle:Default:terminos }

fao_main_search:
    pattern:  /search
    defaults: { _controller: FaoMainBundle:Default:search }
    methods:  [GET, HEAD]

fao_main_show:
    pattern: /{id}/show
    defaults: { _controller: FaoMainBundle:Default:show }

fao_main_category:
    pattern: /category
    defaults: { _controller: FaoMainBundle:Default:category }

fao_main_category_show:
    pattern: /category/{id}/show
    defaults: { _controller: FaoMainBundle:Default:categoryshow }


#fao_main_docs:
#    pattern:  /documents
#    defaults: { _controller: FaoMainBundle:Default:docs }
