parameters:
#    fao_main.example.class: Fao\MainBundle\Example

services:
#    fao_main.example:
#        class: %fao_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
