services:
    fao.main.admin.docs:
        class: Fao\MainBundle\Admin\DocsAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Documento, label: Documento }
        arguments: [null,  Fao\MainBundle\Entity\Docs, FaoMainBundle:DocsAdmin]
        calls:
          - [setSecurityContext,[@security.context]]
          - [setPoolFormatter,[@sonata.formatter.pool]]