<?php

namespace Fao\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocsRepository extends EntityRepository
{
}
